/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package at.yawk.felix.event;

/**
 * Exception handler that is used for managing exceptions generated by EventHandlers.
 *
 * @author Jonas Konrad (yawkat)
 */
public interface ExceptionHandler {
    /**
     * Default implementation that uses printStackTrace to print the exception to console.
     */
    @SuppressWarnings("Convert2Lambda")
    public static final ExceptionHandler PRINT_TRACE = new ExceptionHandler() {
        @SuppressWarnings("CallToPrintStackTrace")
        @Override
        public <Event> void onException(Event event, Throwable throwable, EventHandler<? super Event> handler) {
            throwable.printStackTrace();
        }
    };

    /**
     * Called when an exception occurs.
     */
    <Event> void onException(Event event, Throwable throwable, EventHandler<? super Event> handler);
}
