package at.yawk.felix.event;

/**
 * Exception handler that is used for managing exceptions generated by EventHandlers.
 *
 * @author Jonas Konrad (yawkat)
 */
public interface ExceptionHandler {
    /**
     * Default implementation that uses printStackTrace to print the exception to console.
     */
    public static final ExceptionHandler PRINT_TRACE = new ExceptionHandler() {
        @Override
        public <Event> void onException(Event event, Throwable throwable, EventHandler<? super Event> handler) {
            throwable.printStackTrace();
        }
    };

    /**
     * Called when an exception occurs.
     */
    <Event> void onException(Event event, Throwable throwable, EventHandler<? super Event> handler);
}
